# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#多帐号YOUTH_HEADER 用#号隔开，其它的用&隔开
name: youth(中青看kan)

on:
  workflow_dispatch:
  schedule:
     - cron: '10 23 * * *'
  watch:
    types: youth

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_BANNER: ${{ secrets.YOUTH_BANNER }}
        YOUTH_BANNER2: ${{ secrets.YOUTH_BANNER2 }}
        YOUTH_BANNER3: ${{ secrets.YOUTH_BANNER3 }}
        YOUTH_BANNER4: ${{ secrets.YOUTH_BANNER4 }}
        YOUTH_BANNER5: ${{ secrets.YOUTH_BANNER5 }}
        YOUTH_BANNER6: ${{ secrets.YOUTH_BANNER6 }}
                
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/whymm/youth-w.git ~/youth-w
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YOUTH_BANNER
        run: |
          cd ~/youth-w
          npm install
      - name: '运行 【中青看点】'
        if: env.YOUTH_BANNER
        run: |
          cd ~/youth-w
          node youth_banner.js
        env:
          YOUTH_BANNER: ${{ secrets.YOUTH_BANNER }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: '运行 【中青看点2】'
        if: env.YOUTH_BANNER2
        run: |
          cd ~/youth-w
          node youth_banner.js
        env:
          YOUTH_BANNER2: ${{ secrets.YOUTH_BANNER2 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: '运行 【中青看点3】'
        if: env.YOUTH_BANNER3
        run: |
          cd ~/youth-w
          node youth_banner.js
        env:
          YOUTH_BANNER3: ${{ secrets.YOUTH_BANNER3 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: '运行 【中青看点4】'
        if: env.YOUTH_BANNER4
        run: |
          cd ~/youth-w
          node youth_banner.js
        env:
          YOUTH_BANNER4: ${{ secrets.YOUTH_BANNER4 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: '运行 【中青看点5】'
        if: env.YOUTH_BANNER5
        run: |
          cd ~/youth-w
          node youth_banner.js
        env:
          YOUTH_BANNER5: ${{ secrets.YOUTH_BANNER5 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: '运行 【中青看点6】'
        if: env.YOUTH_BANNER6
        run: |
          cd ~/youth-w
          node youth_banner.js
        env:
          YOUTH_BANNER6: ${{ secrets.YOUTH_BANNER6 }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}   
          
