# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#多帐号YOUTH_HEADER 用#号隔开，其它的用&隔开
name: youths

on:
  workflow_dispatch:
  schedule:
     - cron: '*/7 */2 * * *'
  watch:
    types: youth

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/whymm/youth-w.git ~/youth-w
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.YOUTH_HEADER
        run: |
          cd ~/youth-w
          npm install
      - name: '运行 【中青看点】'
        if: env.YOUTH_HEADER
        run: |
          cd ~/youth-w
          node youths.js
        env:
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
          YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
              
